### ISSUE TITLE
SPV3.2 Loader GUI

### ISSUE THREAD

**Issue by yumiris** [yumiris/HXE#14]
For any masochist who's curious to inspect the GUI, the rabbit hole is this way:

https://cgit.n2.network/spv3.gui/

```
THE SPV3 GUI
============

This repository contains the source for the SPV3 GUI, which is a simple
front-end to the SPV3 CLI. The CLI contains the main logic for the
entire loader, and the GUI merely serves to hide all of that away behind
a pretty interface.

One would argue that the logic should be extracted into a shared
library, rather than have the GUI simply call the CLI; however, the GUI
is an after-thought and is designed to be as simple as possible. In
essence, it just calls the CLI with the relevant arguments.
```

The distribution is done in the same fashion as the CLI -- compiled binaries can be found here:

https://dist.n2.network/spv3.gui/

**Comment by MirisWisdom** [comment]
Professional UX and UI planning, prototyping and development went into developing it:

![image](https://user-images.githubusercontent.com/10241434/56089813-4e819d00-5ecb-11e9-9c78-201573714f05.png)
