### ISSUE TITLE
Campaign Resume

### ISSUE THREAD

**Issue by yumiris** [yumiris/HXE#2]
For the loader to resume the campaign, it needs to declare the last played mission as an integer in the `initc.txt` file. A list of the SPV3.2 campaign maps & their respective integer identifiers will need to be specified.

The current documentation only focuses on the 3.1 maps:

```md
SPV3.2 Campaign
===============

The global variable used is `f3`.

The table below declares the global variable value (ID) in the `initc`
for each SPV3 map name.

  Map Name           ID
  ------------------ ----
  spv3a10            1
  spv3a30            2
  spv3a50            3
  spv3b30            4
  spv3b40            5
  spv3c10            6
  spv3c20            7
  spv3c40            8
  spv3d20            9
  spv3d30\_evolved   10
  spv3d40            11
```

A new list will need to be created to cover the additional 3.2 campaign maps.

@SubhadeepJasu - got anything in mind?

**Comment by SubhadeepJasu** [comment]
```MD
  Map Name           ID
  ------------------ ----
  spv3a10            1
  spv3a30            2
  spv3a50            3
  spv3b30            4
  spv3b30_evolved    5
  spv3b40            6
  spv3c10            7
  spv3c20            8
  spv3c40            9
  spv3d20            10
  spv3d25            11
  spv3d30            12
  spv3d30_evolved    13
  spv3d40            14
  
  lumoria_a          15
  lumoria_b          16
  lumoria_cd         17
```

**Comment by MirisWisdom** [comment]
Excellent, thank you. Wouldn't the Firefight maps also be included, or should they be treated differently?

**Comment by SubhadeepJasu** [comment]
AFAIK they won't have resume capability. I'll need to confirm that with Masterz.

**Comment by yumiris** [comment]
Not a problem. If the Firefight maps will be resumed as well, please 
write a list of the map filenames and their respective identifiers here.

---

This is what we've got so far:

https://github.com/yumiris/SPV3/blob/bd559916d31eb14c6b5f05ad4d84b07fe3845249/doc/loader.txt#L73-L91

**Comment by MirisWisdom** [comment]
Not a problem. If the Firefight maps will be resumed as well, please
write a list of the map filenames and their respective identifiers here.

This is what we've got so far:

https://github.com/yumiris/SPV3/blob/bd559916d31eb14c6b5f05ad4d84b07fe3845249/doc/loader.txt#L73-L91

**Comment by SubhadeepJasu** [comment]
I have just got confirmation that firefight maps won't have resume capability. You die, you start from beginning.

**Comment by MirisWisdom** [comment]
Better workaround: just don't die.

**Comment by SubhadeepJasu** [comment]
That's the spirit of firefight. There's no second chance. How long can you survive?

**Comment by MirisWisdom** [comment]
As long as SPV3 decides to not crash!

**Comment by SubhadeepJasu** [comment]
That's just unfortunate.

**Comment by yumiris** [comment]
Declaring variables within the initc.txt file is done like this:

```lisp
set f3 = 10
```

Correct?

**Comment by MirisWisdom** [comment]
@SubhadeepJasu 

1. Start any SPV3 map with any difficulty.
2. Save your progress, and keep a note of the chosen map & difficulty (don't tell me).
3. Make a copy of your `savegame.bin` in your HCE profile folder.
4. Choose another map and difficulty.
5. Save again, and keep a note of the new map & difficulty (don't tell me).
6. Upload the `savegame.bin` files here.

I'd take care of it myself but I'm currently away from my PC. If I get back to you with the correct maps & difficulties, then the loader's progress is going well.

**Comment by SubhadeepJasu** [comment]
[savegame.zip](https://github.com/yumiris/SPV3/files/2972959/savegame.zip)

**Comment by SubhadeepJasu** [comment]
Decode this and get to the next clue.

**Comment by MirisWisdom** [comment]
@SubhadeepJasu 

![image](https://user-images.githubusercontent.com/10241434/54463719-f150d980-47ae-11e9-8d7a-4b75b39b5807.png)

**Comment by SubhadeepJasu** [comment]
CORRECT
