### ISSUE TITLE
Passthrough -path parameter as-is to Halo's executable

### ISSUE THREAD

**Issue by VoidsShadow** [yumiris/HXE#31]
HXE currently breaks portability for Halo by changing the -path parameter to explicit.

When `-path .\profiles` is passed to haloce.exe/halo.exe without HXE, this carries over to  the paths in the LastProfile and waypoint files. So, the path within these files would be relative e.g. `.\profiles\savegames\New001\New001`
Note: I'm using 'waypoint' to refer to the files with the profile's name as the file name.

HXE takes the -path parameter and changes it to an explicit path
`"J:\Games\Halo Custom Edition\hxe.exe" -path .\temp`
is passed to Halo as 
`-path "J:\Games\Halo Custom Edition\temp"`
and would be written to the files as 
`J:\Games\Halo Custom Edition\profiles\savegames\New001\New001`

Obviously, this would cause profiles to not load properly when the paths are changed from PC to PC.

**Comment by BinToss** [comment]
This issue *might* be exclusive to my ProfileGen fork.

**Comment by BinToss** [comment]
The cause of this issue is https://github.com/yumiris/HXE/blob/ae70eaa1e8b631fd72efa4e1ec6d0b2eb47d34fd/src/HCE/Executable.cs#L154
GetFullPath should be used only where the full path is needed and the original variable should be unchanged when doing so.
