### ISSUE TITLE
USB Flash Drive

### ISSUE THREAD

**Issue by Stuxnet233** [yumiris/HXE#5]
Hello, I have downloaded CE and copied the files over to my flash drive as there was no way to extract the files directly to the drive. I then confirmed that the files were on the pc and extracted SPV3 directly to the drive, and confirm there as well. I opened the launcher, then hit launch SPV3, but to no avail. I went to the reddit page and saw the update link and got this error message after I opened it. What do I do?
![JPEG_20190314_200459](https://user-images.githubusercontent.com/45337245/54400168-f3744480-4697-11e9-9b29-16c569e5f318.jpg)

**Comment by MirisWisdom** [comment]
According to a nearby ant, it seems like the error is hinting at the launcher not being in the same folder as SPV3. Mind sending me a screenshot of the files in the SPV3 folder located on your USB Flash Drive?

Cheers!

**Comment by MirisWisdom** [comment]
@Stuxnet233 - as a follow-up to the above response, can you also confirm that the launcher you've downloaded (spv3.exe) is located in the SPV3 folder on your USB drive?

Miris

**Comment by Stuxnet233** [comment]
Hey, is there another way to communicate?

**Comment by MirisWisdom** [comment]
I only use emails, along with responding on GitHub issues or Reddit posts/messages when necessary, heh.

**Comment by Stuxnet233** [comment]
I ask because I sent the pics, but it said hey, FiLe To LaRgE, and when I
tried to send the one by one, I sent them to the alert email, not you. I
was just asking so I have a easier time, but no worries

**Comment by MirisWisdom** [comment]
Upload them here https://imgur.com/ -- and paste the links in the reply. That should circumvent the email limits. :P

**Comment by Stuxnet233** [comment]
Thanks :)

**Comment by Stuxnet233** [comment]
File screenshots https://imgur.com/gallery/qLGid0e

**Comment by MirisWisdom** [comment]
Looking at your setup, running SPV3.exe from the SPV3 folder on your USB should start it up without any issues. If you get any errors, send 'em over.

Miris

**Comment by Stuxnet233** [comment]
That's the thing, when I hit launch, nothing happens. When I tried to
update it I got an error message

**Comment by Stuxnet233** [comment]
Error https://imgur.com/a/CY8Ae6R

**Comment by MirisWisdom** [comment]
Please send me the link to the Reddit thread you've mentioned in your 
original post.
