### ISSUE TITLE
Installation & Compilation

### ISSUE THREAD

**Issue by yumiris** [yumiris/HXE#6]
This issue focuses on testing out & discussing the compilation/installation procedures. In essence, you _compile_ the SPV3 data to packages, and the users will _install_ the data from these packages to run SPV3.

The following commands should be invoked from a terminal/command line prompt:

```sh
   # compiler
    .\SPV3.CLI.exe compile "C:\Target" # compiles data in the working directory to c:\target

   # installer
    .\SPV3.CLI.exe install "C:\Target" # installs packages in the working directory to c:\target
```

For both commands, it is expected for the SPV3.CLI executable to be present in the directories containing the relevant data.

---

- @VoidsShadow, the installer now writes the target's absolute path to `%APPDATA%\SPV3\install.txt`; and
- @lionirdeadman, feel free to test out the compiling & installing on Linux, as filenames are no longer uppercased.

---

```
COMPILER INFORMATION
--------------------

The compiler handles the preparation of SPV3 data for distribution and
installation. It accomplishes this by DEFLATE-compressing all of the
subdirectories in the source directory to individual packages in the
target directory.

It also adds an entry for the subdirectory in the manifest: this entry
declares the relative path of the subdirectory to the source directory,
the name of the package, and the list of files the subdirectory
contains.
```

```
INSTALLER INFORMATION
---------------------

The installer handles the extraction of data from the DEFLATE packages -
which have been created by the compiler - to the filesystem. It relies
on the generated manifest for inferring which packages are installable,
and loops through each package to install it to the filesystem.

Additionally, it also verifies if files within packages already exist at
the target destination, and if it finds the file, then it will delete it
before installing the package. This is done to practically handle
reinstall scenarios.

To permit other programs to determine the path which SPV3 is installed
to, the installer also creates a text file which contains the absolute
path of the directory which SPV3 is installed to.
```

**Comment by yumiris** [comment]
Compiled CLI binary can be downloaded from [here](https://github.com/yumiris/SPV3/files/2974759/SPV3.CLI.-.ab97e84.zip)!

**Comment by yumiris** [comment]
@SubhadeepJasu - In Syncthing, the latest binary can be found in `\programs\SPV3\bin.zip`.

**Comment by SubhadeepJasu** [comment]
Forwarded to Masterz

**Comment by SubhadeepJasu** [comment]
I'll relay back

**Comment by SubhadeepJasu** [comment]
Also a quick suggestion. Can we write the SPV3 root location in an environment variable, if it's not too difficult. That's just to future proof stuff. We may need it.

**Comment by MirisWisdom** [comment]
@SubhadeepJasu 

The location is already written in `%APPDATA%\SPV3\install.txt`, rather than in an environment variable. Would there by any advantages to using an env var, in this scenario?

**Comment by SubhadeepJasu** [comment]
nvm, i got it.

**Comment by MirisWisdom** [comment]
Excellent. I've updated the main post in hopes of making things a little clearer.

**Comment by SubhadeepJasu** [comment]
umm, read the other issue I created. Pls
