### ISSUE TITLE
Mechanism for Locking SPV3.2 Maps

### ISSUE THREAD

**Issue by yumiris** [yumiris/HXE#9]
the answer is no

**Comment by SubhadeepJasu** [comment]
lol

**Comment by MirisWisdom** [comment]
On a serious side, why exactly are we continuing to force people to use the loader?

**Comment by SubhadeepJasu** [comment]
I just asked Masterz the same question.

**Comment by MirisWisdom** [comment]
@SubhadeepJasu, what's the answer? 🤔

**Comment by SubhadeepJasu** [comment]
Silence

**Comment by MirisWisdom** [comment]
That's one way to describe the locking mechanism - glad we're no longer locking SPV3.

**Comment by SubhadeepJasu** [comment]
He moved to a different question. IDK.

**Comment by SubhadeepJasu** [comment]
His answer is yes. The launcher may not have to participate in the locking. but it needs to remove initc ones its done working, or when the launcher exits.

**Comment by MirisWisdom** [comment]
Why does it need to do that? 🤔

**Comment by SubhadeepJasu** [comment]
Now there are LUA stuff going on. and he doesn't want it to fuck up other maps in the system. Also that people must get as close to a definitive experience as possible for his hardware, without the launcher spv3 will pretty much play in the lowest quality mode. People might complain that the trailers are lying about the graphics. Also the Visor is on my default. People might complain that there is no way to turn it off.

**Comment by MirisWisdom** [comment]
Other maps outside of SPV3? They shouldn't be affected if SPV3 is kept separate from HCE.

We've had people being annoyed by SPV3 forcing the use of loader. Perhaps we could replace the locking mechanism with a warning like:

```It seems you haven't used the loader to run SPV3. You will likely run into quality problems if you continue. Do you wish to continue? [yes/no]```

How's that sound?

**Comment by SubhadeepJasu** [comment]
That was the original plan
Not sure how to do it tho.

**Comment by MirisWisdom** [comment]
Same thing as what we currently have, except you resume the map instead of exiting it. Perhaps temporarily store the map that was going to be played in a variable, and have that `err` map use it? 🤔

**Comment by SubhadeepJasu** [comment]
hmm that could work

**Comment by MirisWisdom** [comment]
the answer ended up being no
